import localFont from "next/font/local";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";
import { Poppins } from "next/font/google";
import AppNavbar from "@/components/navbar";
import StoreProvider from "@/redux/Provider";
import Footer from "@/components/footer";
import FullScreenLoader from "@/components/loader";
import Loader from "@/components/loader";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata = {
  title: "Travel.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={poppins.className}>
          <div className="main-layout">
            <AppNavbar />
            {children}
            <Loader />
            <Footer />
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
